### ISSUE TITLE
Changelog and tag versions

### ISSUE THREAD

**Issue by sgerrand** [Adzz/ecto_morph#46]
Tagging versions and adding a changelog file (with information on changes per version) to this repository will make it easier for services like Dependabot to determine the impact of changes and provide meaningful information to consumers of this package. At the moment these automated update proposals look like this:

<img width="919" alt="2021-02-11 Dependabot update ecto_morph" src="https://user-images.githubusercontent.com/203366/107618836-1fb0eb00-6c4a-11eb-906c-a5e689187891.png">

**Comment by Adzz** [comment]
Ah great shout. I will do just that for future releases.

**Comment by sgerrand** [comment]
🎉 Added in ad5b4e98696a6c9d9ffd8ed0d0fcae918956018a

**Comment by sgerrand** [comment]
Could you tag the version as well? 🤲

**Comment by Adzz** [comment]
Tag added! I've not done either before so thanks for the suggestion.

**Comment by sgerrand** [comment]
That's great. Thanks again!
